CREATE TABLE saison (
    id UUID PRIMARY KEY,
    name INTEGER NOT NULL UNIQUE,
    version BIGINT NOT NULL DEFAULT 0,
    erstellt_am TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    geaendert_am TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
