spring:
  application:
    name: wettkampf-server
  datasource:
    url: ${WETTKAMPF_DB_URL}
    username: ${WETTKAMPF_DB_BENUTZER}
    password: ${WETTKAMPF_DB_PASSWORT}
  flyway:
    enabled: true

server:
  port: ${WETTKAMPF_SERVER_PORT:8002}

wettkampf:
  konto:
    name: ${WETTKAMPF_KONTO_NAME:}
    initiales-passwort: ${WETTKAMPF_KONTO_PASSWORT:}
  sitzungsdauer: ${WETTKAMPF_SITZUNGSDAUER:PT12H}
